# Generated by Django 5.2.8 on 2025-11-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_usuario_activo_alter_calificacion_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
