# Generated by Django 5.1.7 on 2025-11-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0004_usuario_bloqueado_usuario_intentos_fallidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
